### ISSUE TITLE
Add Grunt WordPress publishing

### ISSUE THREAD

**Issue by moorscode** [Yoast/yoast-test-helper#13]
As this plugin will be publicly available, we want to have a simple way of publishing new releases.

Todo, use Grunt to:
- Create an Artifact folder (+zip)
- Easy version bump command
- Add `readme.txt`
- `grunt deploy:master`
- `grunt deploy:trunk`

WordPress SEO is the repository to look at for reference.
The Grunt plugin should be used for the update/set-version commands (https://github.com/Yoast/plugin-grunt-tasks/pull/2)

**Comment by dutchmartin** [comment]
all other things regarding this issue can be posted in #23
