### ISSUE TITLE
Add WP-CLI commands

### ISSUE THREAD

**Issue by crstauf** [Yoast/yoast-test-helper#133]
It would save so much time if the tools were available via WP-CLI. Recently had to reset indexable tables across a network of 70+ sites, and was painstaking to login to each site and perform the operation, especially knowing that it would've only been a few minutes if there were CLI commands.

**Comment by jeroenrotty** [comment]
Hey @crstauf,

Please know that our `wp yoast index` command has a `--network` parameter. See https://developer.yoast.com/features/wp-cli/reindex-indexables/
