### ISSUE TITLE
Add an option to direct MyYoast requests to staging.

### ISSUE THREAD

**Issue by herregroen** [Yoast/yoast-test-helper#50]
There should be an option in the test helper which, if enabled, directs any request that would have gone to "https://my.yoast.com" instead to "https://staging-my.yoast.com".

The easiest way to achieve this would be to make the subdomain of all these URLs filterable in the plugin so that it can be replaced with "staging-my" by the test helper.

This would allow us to easily test features such as:
- New morphology releases
- Changes to licensing
- Features such as the new plugin installation flow which feature a lot of interaction between MyYoast and the plugin.

**Comment by diedexx** [comment]
We can use the `requests-requests.before_request` action to change the $url to the MyYoast staging domain _if_ the original request is going to be sent to my.yoast.com. Here's an example how Jetpack uses this filter to achieve the same goal. https://github.com/Automattic/jetpack/blob/792b26b5539d07cc35fdd93567942f2ad481eef2/_inc/jetpack-server-sandbox.php#L63

**Comment by diedexx** [comment]
The option should be a dropdown of 4 options:
- live
- staging
- staging-plugins
- staging-platform

**Comment by diedexx** [comment]
A new tag (1.2.5 or the next minor release) should be created and pushed with
`git tag -a 1.2.5` `git push origin master --tags`

on yoast.com master: run `composer require yoast/yoast-test-helper --dev` and push this to master and merge this to all both staging-plugins and staging-platform with `git checkout staging-plugins && git pull origin master`.

**Comment by diedexx** [comment]
When testing this: when visiting the `premium` page in the plugin, a license request will be fired. If you have a site active on prod, and not active in dev you should quickly verify that the new option works and your license check is redirected to your local site
