### ISSUE TITLE
Release yoast-test-helper properly

### ISSUE THREAD

**Issue by boblinthorst** [Yoast/yoast-test-helper#55]
When https://github.com/Yoast/yoast-test-helper/issues/50 was finished, a release of the yoast-test-helper was necessary. The release process was executed wrongly though.

- These were the followed instructions: 
  - https://github.com/Yoast/yoast-test-helper/issues/50#issuecomment-544504359
- These were the instructions that should've been followed: 
  - https://github.com/Yoast/Wiki/wiki/Package-Release-Process-(non-monorepo)#releasing-yoast-test-helper

Can you do the steps that you (potentially) missed, and rebuild the zip with grunt artifact ? If it’s easier to do an new ‘empty’ 1.2.7 release, that’s fine as well

Work together with the plugin-team if these instructions are insufficient.

**Comment by diedexx** [comment]
@dariaknl says that this doesn’t need to be fixed now, but it is absolutely required when testing the plugin installation flow

**Comment by jdevalk** [comment]
Done: https://github.com/Yoast/yoast-test-helper/releases/tag/1.3
