### ISSUE TITLE
Undefined index in WordPress_Plugin_Version_Control.php

### ISSUE THREAD

**Issue by dariaknl** [Yoast/yoast-test-helper#62]
The issue is found during testing of 13.2 release candidates. For Site Health feature upgrade routines should be tested.

### How can we reproduce this behavior?
1. Download zip, install and activate Yoast Test Helper 1.4.
2. Install and activate Yoast SEO 13.2-RC1 
3. Go to Yoast Test Helper

`Notice: Undefined index: version in /srv/www/local/public_html/wp-content/plugins/yoast-test-helper/src/WordPress_Plugin_Version_Control.php on line 159
`

<img width="675" alt="Screenshot 2020-02-20 at 11 25 34" src="https://user-images.githubusercontent.com/19681708/74925026-ca921e80-53d3-11ea-819c-cc195368acc7.png">

**Comment by hansjovis** [comment]
These notices do not impact the functionality. 

We already catch when no previous version of a plugin can be found and output an empty version string if this is the case.

I have pushed this back to the backlog after discussing it with @JessieHenkes .
