### ISSUE TITLE
Save the permalinks structure after changing custom post types

### ISSUE THREAD

**Issue by igorschoester** [Yoast/yoast-test-helper#63]
## Describe the feature you'd like

When the setting `Enable post types & taxonomies.` is changed, also update the permalink structure in WordPress, preventing 404s in the docker environment.

## Reproduce

1. Disable `Enable post types & taxonomies.`.
1. Save the WP permalink settings.
1. Enable `Enable post types & taxonomies.`.
1. Go to a frontend page of a book for example and see a 404 page. Tip, use the sitemap: http://basic.wordpress.test/book-sitemap.xml

The workaround is manually saving the permalink settings again.

**Comment by moorscode** [comment]
https://developer.wordpress.org/reference/functions/flush_rewrite_rules/
