### ISSUE TITLE
Reset the indexables_indexation_completed flag

### ISSUE THREAD

**Issue by andizer** [Yoast/yoast-test-helper#94]
We have to add logic to reset the:
- [ ] Reset `indexables_indexation_completed` flag
- [ ] Clearing the `indexables_indexation_reason` See https://github.com/Yoast/wordpress-seo/issues/15440
- [ ] Remove the transient that holds the query result for the indexables (for showing the notification).

**Comment by IreneStr** [comment]
This issue has been moved to Jira: https://yoast.atlassian.net/browse/P2-29
